"""empty message

Revision ID: 320e4291e882
Revises: dc5a09050634
Create Date: 2024-06-08 02:41:42.512880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320e4291e882'
down_revision = 'dc5a09050634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
