"""empty message

Revision ID: 3c8e1edc2487
Revises: f556fab94812
Create Date: 2024-05-15 23:25:17.983057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8e1edc2487'
down_revision = 'f556fab94812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_feed_back',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('visit_type', sa.String(length=60), nullable=False),
    sa.Column('time_visit', sa.String(length=60), nullable=False),
    sa.Column('date_visit', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=60), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('db_order_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_order_foods', schema=None) as batch_op:
        batch_op.drop_column('quality')

    op.drop_table('tb_feed_back')
    # ### end Alembic commands ###
