"""empty message

Revision ID: 41994bf0070d
Revises: 6446ed1b84fd
Create Date: 2024-06-03 22:22:43.538473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41994bf0070d'
down_revision = '6446ed1b84fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.drop_column('ranting')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranting', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
