"""empty message

Revision ID: 55ad01c268b0
Revises: b732f737dd78
Create Date: 2024-05-16 19:39:00.717172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ad01c268b0'
down_revision = 'b732f737dd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['info'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_food', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('info')

    # ### end Alembic commands ###
