"""empty message

Revision ID: 73450ba192cc
Revises: b768ef92e1bf
Create Date: 2024-06-12 22:43:13.850620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73450ba192cc'
down_revision = 'b768ef92e1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brithDay', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('brithDay')

    # ### end Alembic commands ###
