"""empty message

Revision ID: 7760154f11b0
Revises: 7078c00a6197
Create Date: 2024-06-19 03:16:58.423258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7760154f11b0'
down_revision = '7078c00a6197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_order', schema=None) as batch_op:
        batch_op.drop_constraint('tb_order_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_order', schema=None) as batch_op:
        batch_op.create_foreign_key('tb_order_ibfk_2', 'tb_user', ['driver_id'], ['id'])

    # ### end Alembic commands ###
