"""empty message

Revision ID: 91b0b71610cc
Revises: eb6a76a7dca0
Create Date: 2024-05-10 00:28:05.587170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b0b71610cc'
down_revision = 'eb6a76a7dca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_shopping_cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('db_shopping_cart_foods',
    sa.Column('shopping_cart_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['tb_food.id'], ),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['tb_shopping_cart.id'], ),
    sa.PrimaryKeyConstraint('shopping_cart_id', 'food_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_shopping_cart_foods')
    op.drop_table('tb_shopping_cart')
    # ### end Alembic commands ###
