"""empty message

Revision ID: a4f316453a5a
Revises: 7760154f11b0
Create Date: 2024-06-21 07:52:53.652733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f316453a5a'
down_revision = '7760154f11b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPickUp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_order', schema=None) as batch_op:
        batch_op.drop_column('isPickUp')

    # ### end Alembic commands ###
