"""empty message

Revision ID: b81b4c88bc24
Revises: 
Create Date: 2024-05-06 15:27:20.359710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81b4c88bc24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_authorization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_name', sa.String(length=50), nullable=False),
    sa.Column('resource_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_roles_auths',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['tb_authorization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'auth_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_roles_auths')
    op.drop_table('tb_role')
    op.drop_table('tb_user')
    op.drop_table('tb_authorization')
    # ### end Alembic commands ###
