"""empty message

Revision ID: d75f4a2fae60
Revises: 4bfd0ad074e5
Create Date: 2024-05-19 11:46:07.812873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd75f4a2fae60'
down_revision = '4bfd0ad074e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tel', sa.String(length=50), nullable=False))
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('tel')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
