"""empty message

Revision ID: eb6a76a7dca0
Revises: d3070f543f04
Create Date: 2024-05-09 23:38:52.457223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6a76a7dca0'
down_revision = 'd3070f543f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_user_order',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tb_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'order_id')
    )
    op.create_table('db_order_foods',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['tb_food.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['tb_order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'food_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_order_foods')
    op.drop_table('db_user_order')
    op.drop_table('tb_order')
    # ### end Alembic commands ###
