"""empty message

Revision ID: f84d508c60b2
Revises: fa3ec998078e
Create Date: 2024-05-10 02:01:03.934206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84d508c60b2'
down_revision = 'fa3ec998078e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_shopping_cart_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_shopping_cart_foods', schema=None) as batch_op:
        batch_op.drop_column('quality')

    # ### end Alembic commands ###
