"""empty message

Revision ID: fa3ec998078e
Revises: 
Create Date: 2024-05-10 01:54:18.848058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3ec998078e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_authorization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_name', sa.String(length=50), nullable=False),
    sa.Column('resource_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('tb_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('db_roles_auths',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['tb_authorization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'auth_id')
    )
    op.create_table('db_user_order',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tb_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'order_id')
    )
    op.create_table('db_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('tb_food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tb_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_name'),
    sa.UniqueConstraint('img')
    )
    op.create_table('tb_shopping_cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_order_foods',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['tb_food.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['tb_order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'food_id')
    )
    op.create_table('db_shopping_cart_foods',
    sa.Column('shopping_cart_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['tb_food.id'], ),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['tb_shopping_cart.id'], ),
    sa.PrimaryKeyConstraint('shopping_cart_id', 'food_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_shopping_cart_foods')
    op.drop_table('db_order_foods')
    op.drop_table('tb_shopping_cart')
    op.drop_table('tb_food')
    op.drop_table('db_user_roles')
    op.drop_table('db_user_order')
    op.drop_table('db_roles_auths')
    op.drop_table('tb_user')
    op.drop_table('tb_role')
    op.drop_table('tb_order')
    op.drop_table('tb_category')
    op.drop_table('tb_authorization')
    # ### end Alembic commands ###
